-- =============================================================
-- Schema: Scientific Journal DB (BIGINT Identity Version)
-- Source: Scimago ETL Import & User Update
-- =============================================================

-- Dá»n dáº¹p cáº¥u trÃºc cÅ© náº¿u tá»“n táº¡i
DROP TABLE IF EXISTS "Journal_Ranking_Subject_Category" CASCADE;
DROP TABLE IF EXISTS "Journal_Ranking" CASCADE;
DROP TABLE IF EXISTS "Ranking_Metric" CASCADE;
DROP TABLE IF EXISTS "Project_Journal" CASCADE;
DROP TABLE IF EXISTS "Subject_Category_Project" CASCADE;
DROP TABLE IF EXISTS "Project" CASCADE;
DROP TABLE IF EXISTS "Sub_Topic" CASCADE;
DROP TABLE IF EXISTS "Keyword_Article" CASCADE;
DROP TABLE IF EXISTS "Keyword" CASCADE;
DROP TABLE IF EXISTS "Author_Article" CASCADE;
DROP TABLE IF EXISTS "Author" CASCADE;
DROP TABLE IF EXISTS "Article" CASCADE;
DROP TABLE IF EXISTS "Topic" CASCADE;
DROP TABLE IF EXISTS "Issue" CASCADE;
DROP TABLE IF EXISTS "Volume" CASCADE;
DROP TABLE IF EXISTS "Journal_Subject_Category" CASCADE;
DROP TABLE IF EXISTS "Journal" CASCADE;
DROP TABLE IF EXISTS "Publisher" CASCADE;
DROP TABLE IF EXISTS "Subject_Category" CASCADE;
DROP TABLE IF EXISTS "Subject_Area" CASCADE;
DROP TABLE IF EXISTS "Zone" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS raw_scimago_journal CASCADE;

-- Drop cÃ¡c kiá»ƒu ENUM cÅ© náº¿u cÃ³
DROP TYPE IF EXISTS role_account CASCADE;
DROP TYPE IF EXISTS status_account CASCADE;
DROP TYPE IF EXISTS auth_provider CASCADE;
DROP TYPE IF EXISTS type_zone CASCADE;
DROP TYPE IF EXISTS source_zone CASCADE;
DROP TYPE IF EXISTS ranking_source CASCADE;
DROP TYPE IF EXISTS ranking_metric_type CASCADE;

-- 1. Táº¡o cÃ¡c kiá»ƒu ENUM
CREATE TYPE "role_account" AS ENUM (
  'STUDENT',
  'LECTURER',
  'RESEARCHER',
  'ADMINISTRATOR'
);

CREATE TYPE "status_account" AS ENUM (
  'INACTIVE',
  'ACTIVE',
  'BANNED'
);

CREATE TYPE "auth_provider" AS ENUM (
  'LOCAL',
  'GOOGLE'
);

CREATE TYPE "type_zone" AS ENUM (
  'COUNTRY',
  'REGION'
);

CREATE TYPE "source_zone" AS ENUM (
  'ISO',
  'SCIMAGO',
  'OPENALEX',
  'INTERNAL'
);

CREATE TYPE "ranking_source" AS ENUM (
  'SCOPUS',
  'WOS',
  'SCIMAGO'
);

CREATE TYPE "ranking_metric_type" AS ENUM (
  'QUARTILE',
  'SCORE',
  'INTEGER'
);

-- 2. Bảng user (Dùng UUID)
CREATE TABLE "user" (
  "user_id" uuid PRIMARY KEY NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar,
  "type" auth_provider,
  "status" status_account,
  "role" role_account,
  "last_name" varchar,
  "first_name" varchar,
  "url_image" varchar,
  "date_of_birth" date,
  "gender" bool
);

-- 2b. Bảng Password_Reset_Token
CREATE TABLE "Password_Reset_Token" (
  "token_id"   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"    uuid NOT NULL,
  "token_hash" varchar(255) NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at"    timestamp NULL,
  "created_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "Password_Reset_Token_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_prt_user_id"    ON "Password_Reset_Token" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_prt_token_hash" ON "Password_Reset_Token" ("token_hash");

-- 3. Báº£ng Project
CREATE TABLE "Project" (
  "project_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "subject_area" bigint,
  "title" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- 4. Báº£ng Project_Keyword (Many-to-Many)
CREATE TABLE "Project_Keyword" (
  "project_id" bigint,
  "keyword_id" bigint,
  PRIMARY KEY ("project_id", "keyword_id")
);

-- 5. Báº£ng Subject_Category_Project
CREATE TABLE "Subject_Category_Project" (
  "project_id" bigint,
  "subject_category_id" bigint,
  PRIMARY KEY ("project_id", "subject_category_id")
);

-- 6. Báº£ng Project_Journal
CREATE TABLE "Project_Journal" (
  "project_id" bigint,
  "journal_id" bigint,
  PRIMARY KEY ("project_id", "journal_id")
);

-- 7. Báº£ng Zone
CREATE TABLE "Zone" (
  "zone_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "name" varchar,
  "type" type_zone,
  "iso_code" varchar,
  "source" source_zone,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_zone_name_type UNIQUE ("name", "type")
);

-- 8. Báº£ng Subject_Area
CREATE TABLE "Subject_Area" (
  "subject_area_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" varchar,
  "description" varchar,
  CONSTRAINT uq_subject_area_name UNIQUE ("display_name")
);

-- 9. Báº£ng Subject_Category
CREATE TABLE "Subject_Category" (
  "subject_category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_area_id" bigint,
  "display_name" varchar,
  "description" varchar,
  CONSTRAINT uq_subject_category_area_name UNIQUE ("subject_area_id", "display_name")
);

-- 10. Báº£ng Journal_Ranking_Subject_Category (Many-to-Many)
CREATE TABLE "Journal_Ranking_Subject_Category" (
  "journal_ranking_id" bigint,
  "subject_category_id" bigint,
  PRIMARY KEY ("journal_ranking_id", "subject_category_id")
);

-- 11. Báº£ng Publisher
CREATE TABLE "Publisher" (
  "publisher_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" varchar,
  "image_url" varchar,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP, -- Äá»•i tá»« datetime Ä‘á»ƒ cháº¡y Ä‘Æ°á»£c trong PostgreSQL
  CONSTRAINT uq_publisher_display_name UNIQUE ("display_name")
);

-- 12. Báº£ng Journal
CREATE TABLE "Journal" (
  "journal_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_id" varchar,
  "publisher_id" bigint,
  "country" bigint,
  "region" bigint,
  "display_name" varchar NOT NULL,
  "type" varchar,
  "is_open_access" bool,
  "is_oa_diamond" bool,
  "coverage" varchar,
  "issn" varchar,
  "scope_detail" varchar,
  
  -- Cá»™t phá»¥c vá»¥ Ä‘á»“ng bá»™ OpenAlex
  "works_synced_at" timestamp,
  "is_deleted" boolean DEFAULT false
);

-- 13. Báº£ng Journal_Subject_Category (Many-to-Many)
CREATE TABLE "Journal_Subject_Category" (
  "journal_id" bigint,
  "subject_category_id" bigint,
  PRIMARY KEY ("journal_id", "subject_category_id")
);

-- 14. Báº£ng Volume
CREATE TABLE "Volume" (
  "volume_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal_id" bigint,
  "volume_number" int,
  "publication_year" int,
  "is_deleted" boolean DEFAULT false
);

-- 15. Báº£ng Issue
CREATE TABLE "Issue" (
  "issue_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "volume_id" bigint,
  "issue_number" varchar,
  "publication_year" int
);

-- 16. Báº£ng Topic
CREATE TABLE "Topic" (
  "topic_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" varchar UNIQUE,
  "score" double precision,
  "subject_area_id" bigint,
  "subject_category_id" bigint
);

-- 17. Báº£ng Article
CREATE TABLE "Article" (
  "article_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version" varchar,
  "issue_id" bigint,
  "title" varchar NOT NULL,
  "abstract" varchar,
  "publication_year" int,
  "doi" varchar,
  "primary_topic" bigint,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "is_deleted" boolean DEFAULT false
);

-- 18. Báº£ng Author
CREATE TABLE "Author" (
  "author_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orcid" varchar UNIQUE,
  "display_name" varchar,
  "url_image" varchar,
  
  -- CÃ¡c cá»™t bá»• sung tá»« OpenAlex
  "openalex_id" varchar UNIQUE,
  "works_count" bigint,  -- Äá»•i sang bigint cho khá»›p DB thá»±c táº¿ vÃ  OpenAlex
  "cited_by_count" bigint,  -- Äá»•i sang bigint
  "h_index" bigint,  -- Äá»•i sang bigint
  "i10_index" bigint,  -- Äá»•i sang bigint
  "last_known_institution" varchar,
  "last_known_institution_id" varchar,
  "homepage_url" varchar,
  "openalex_synced_at" timestamp
);

-- 19. Báº£ng Author_Article
CREATE TABLE "Author_Article" (
  "author_id" bigint,
  "article_id" bigint,
  PRIMARY KEY ("author_id", "article_id")
);

-- 20. Báº£ng Keyword
CREATE TABLE "Keyword" (
  "keyword_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" varchar UNIQUE
);

-- 21. Báº£ng Keyword_Article
CREATE TABLE "Keyword_Article" (
  "keyword_id" bigint,
  "article_id" bigint,
  "score" double precision,
  PRIMARY KEY ("keyword_id", "article_id")
);

-- 22. Báº£ng Sub_Topic
CREATE TABLE "Sub_Topic" (
  "article_id" bigint,
  "topic_id" bigint,
  PRIMARY KEY ("article_id", "topic_id")
);

-- 23. Báº£ng Ranking_Metric
CREATE TABLE "Ranking_Metric" (
  "metric_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "display_name" varchar,
  "metric_type" ranking_metric_type,
  "description" varchar
);

-- 24. Báº£ng Journal_Ranking
CREATE TABLE "Journal_Ranking" (
  "journal_ranking_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal_id" bigint NOT NULL,
  "subject_category_id" bigint,
  "source" ranking_source NOT NULL DEFAULT 'SCIMAGO',
  "metric_id" bigint NOT NULL,
  "year" int NOT NULL,
  "value_txt" varchar,
  "value_int" int,
  "value_float" double precision,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- 25. Báº£ng staging raw_scimago_journal
CREATE TABLE raw_scimago_journal (
    raw_id                  BIGSERIAL PRIMARY KEY,
    import_batch_id         UUID      NOT NULL,
    rank_txt                TEXT,
    source_id               TEXT,
    title                   TEXT,
    type                    TEXT,
    issn                    TEXT,
    publisher               TEXT,
    open_access             TEXT,
    open_access_diamond     TEXT,
    sjr                     TEXT,
    h_index                 TEXT,
    total_docs_current_year TEXT,
    total_docs_3years       TEXT,
    total_refs              TEXT,
    total_cites_3years      TEXT,
    citable_docs_3years     TEXT,
    cites_doc_2years        TEXT,
    ref_doc                 TEXT,
    country                 TEXT,
    region                  TEXT,
    categories              TEXT,
    areas                   TEXT,
    raw_json                JSONB,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Comments on tables and columns
COMMENT ON COLUMN "user"."password" IS 'Máº­t kháº©u Ä‘Ã£ mÃ£ hÃ³a bÄƒm (hashing)';
COMMENT ON COLUMN "user"."type" IS 'PhÆ°Æ¡ng thá»©c Ä‘Äƒng nháº­p';
COMMENT ON COLUMN "user"."status" IS 'Tráº¡ng thÃ¡i tÃ i khoáº£n';
COMMENT ON COLUMN "user"."gender" IS '0: Ná»¯, 1: Nam';
COMMENT ON COLUMN "Zone"."code" IS 'VÃ­ dá»¥: VN, ASIA, EU, GLOBAL';
COMMENT ON COLUMN "Zone"."name" IS 'TÃªn quá»‘c gia hoáº·c khu vá»±c';
COMMENT ON COLUMN "Subject_Area"."display_name" IS 'LÄ©nh vá»±c lá»›n (VÃ­ dá»¥: Medicine, Social Sciences tá»« Scimago)';
COMMENT ON COLUMN "Subject_Category"."subject_area_id" IS 'Thuá»™c vá» lÄ©nh vá»±c lá»›n nÃ o';
COMMENT ON COLUMN "Subject_Category"."display_name" IS 'ChuyÃªn ngÃ nh háº¹p (VÃ­ dá»¥: Oncology, Cultural Studies)';
COMMENT ON COLUMN "Journal"."source_id" IS 'ID gá»‘c tá»« Scimago (Sourceid) hoáº·c OpenAlex Ä‘á»ƒ Ä‘á»“ng bá»™';
COMMENT ON COLUMN "Journal"."country" IS 'Quá»‘c gia/khu vá»±c quáº£n lÃ½ táº¡p chÃ­';
COMMENT ON COLUMN "Journal"."region" IS 'Quá»‘c gia/khu vá»±c quáº£n lÃ½ táº¡p chÃ­';
COMMENT ON COLUMN "Journal"."display_name" IS 'TÃªn táº¡p chÃ­';
COMMENT ON COLUMN "Journal"."type" IS 'journal, book series, conference and proceedings, trade journal';
COMMENT ON COLUMN "Journal"."is_open_access" IS 'TrÆ°á»ng Open Access (Yes/No) tá»« Scimago 2025';
COMMENT ON COLUMN "Journal"."is_oa_diamond" IS 'TrÆ°á»ng Open Access Diamond (Yes/No) tá»« Scimago 2025';
COMMENT ON COLUMN "Journal"."coverage" IS 'Thá»i gian bao phá»§ dá»¯ liá»‡u (VÃ­ dá»¥: 1950-2026)';
COMMENT ON COLUMN "Article"."version" IS 'PhiÃªn báº£n bÃ i bÃ¡o';
COMMENT ON COLUMN "Author"."orcid" IS 'MÃ£ Ä‘á»‹nh danh quá»‘c táº¿ cá»§a tÃ¡c giáº£';
COMMENT ON COLUMN "Keyword_Article"."score" IS 'Trá»ng sá»‘ cá»§a tá»« khÃ³a Ä‘á»‘i vá»›i riÃªng bÃ i bÃ¡o nÃ y';
COMMENT ON COLUMN "Ranking_Metric"."code" IS 'MÃ£ Ä‘á»‹nh danh chá»‰ sá»‘ Ä‘á»ƒ map code há»‡ thá»‘ng';
COMMENT ON COLUMN "Ranking_Metric"."display_name" IS 'TÃªn hiá»ƒn thá»‹ tá»« file excel';
COMMENT ON TABLE "Journal_Ranking" IS 'Báº£ng lÆ°u trá»¯ Ä‘á»™ng toÃ n bá»™ chá»‰ sá»‘ xáº¿p háº¡ng theo nÄƒm cá»§a Táº¡p chÃ­';
COMMENT ON COLUMN "Journal_Ranking"."subject_category_id" IS 'Null náº¿u lÃ  chá»‰ sá»‘ chung cá»§a Táº¡p chÃ­ (nhÆ° H-index, Total Docs). CÃ³ giÃ¡ trá»‹ náº¿u lÃ  Rank hoáº·c Quartile riÃªng cá»§a Táº¡p chÃ­ trong ChuyÃªn ngÃ nh Ä‘Ã³';
COMMENT ON COLUMN "Journal_Ranking"."year" IS 'VÃ­ dá»¥: 2025';
COMMENT ON COLUMN "Journal_Ranking"."value_txt" IS 'LÆ°u giÃ¡ trá»‹ náº¿u metric_type = QUARTILE (VÃ­ dá»¥: Q1)';
COMMENT ON COLUMN "Journal_Ranking"."value_int" IS 'LÆ°u giÃ¡ trá»‹ náº¿u metric_type = INTEGER (VÃ­ dá»¥: 236, 4331)';
COMMENT ON COLUMN "Journal_Ranking"."value_float" IS 'LÆ°u giÃ¡ trá»‹ náº¿u metric_type = SCORE (VÃ­ dá»¥: 104.065, 46.34)';

-- RÃ ng buá»™c Foreign Key
ALTER TABLE "Project" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Project" ADD FOREIGN KEY ("subject_area") REFERENCES "Subject_Area" ("subject_area_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Project_Keyword" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Project_Keyword" ADD FOREIGN KEY ("keyword_id") REFERENCES "Keyword" ("keyword_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Subject_Category_Project" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Subject_Category_Project" ADD FOREIGN KEY ("subject_category_id") REFERENCES "Subject_Category" ("subject_category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Project_Journal" ADD FOREIGN KEY ("project_id") REFERENCES "Project" ("project_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Project_Journal" ADD FOREIGN KEY ("journal_id") REFERENCES "Journal" ("journal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Subject_Category" ADD FOREIGN KEY ("subject_area_id") REFERENCES "Subject_Area" ("subject_area_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Journal_Ranking_Subject_Category" ADD FOREIGN KEY ("journal_ranking_id") REFERENCES "Journal_Ranking" ("journal_ranking_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal_Ranking_Subject_Category" ADD FOREIGN KEY ("subject_category_id") REFERENCES "Subject_Category" ("subject_category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Journal" ADD FOREIGN KEY ("publisher_id") REFERENCES "Publisher" ("publisher_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal" ADD FOREIGN KEY ("country") REFERENCES "Zone" ("zone_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal" ADD FOREIGN KEY ("region") REFERENCES "Zone" ("zone_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Journal_Subject_Category" ADD FOREIGN KEY ("journal_id") REFERENCES "Journal" ("journal_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal_Subject_Category" ADD FOREIGN KEY ("subject_category_id") REFERENCES "Subject_Category" ("subject_category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Volume" ADD FOREIGN KEY ("journal_id") REFERENCES "Journal" ("journal_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Issue" ADD FOREIGN KEY ("volume_id") REFERENCES "Volume" ("volume_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Topic" ADD FOREIGN KEY ("subject_area_id") REFERENCES "Subject_Area" ("subject_area_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Topic" ADD FOREIGN KEY ("subject_category_id") REFERENCES "Subject_Category" ("subject_category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Article" ADD FOREIGN KEY ("issue_id") REFERENCES "Issue" ("issue_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Article" ADD FOREIGN KEY ("primary_topic") REFERENCES "Topic" ("topic_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Author_Article" ADD FOREIGN KEY ("author_id") REFERENCES "Author" ("author_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Author_Article" ADD FOREIGN KEY ("article_id") REFERENCES "Article" ("article_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Keyword_Article" ADD FOREIGN KEY ("keyword_id") REFERENCES "Keyword" ("keyword_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Keyword_Article" ADD FOREIGN KEY ("article_id") REFERENCES "Article" ("article_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Sub_Topic" ADD FOREIGN KEY ("article_id") REFERENCES "Article" ("article_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Sub_Topic" ADD FOREIGN KEY ("topic_id") REFERENCES "Topic" ("topic_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Journal_Ranking" ADD FOREIGN KEY ("journal_id") REFERENCES "Journal" ("journal_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal_Ranking" ADD FOREIGN KEY ("subject_category_id") REFERENCES "Subject_Category" ("subject_category_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Journal_Ranking" ADD FOREIGN KEY ("metric_id") REFERENCES "Ranking_Metric" ("metric_id") DEFERRABLE INITIALLY IMMEDIATE;

-- Unique index cho Journal_Ranking (sá»­ dá»¥ng coalesce Ä‘á»ƒ chá»‘ng trÃ¹ng láº·p dÃ²ng khi import Ä‘Ã¨ dá»¯ liá»‡u)
CREATE UNIQUE INDEX IF NOT EXISTS uq_journal_ranking_prevent_dupes 
ON "Journal_Ranking" (
    journal_id, 
    source, 
    metric_id, 
    year, 
    coalesce(value_txt, ''), 
    coalesce(value_int, 0), 
    coalesce(value_float, 0)
);

-- Index cho raw_scimago_journal Ä‘á»ƒ tá»‘i Æ°u hÃ³a truy váº¥n export report trÃ¡nh bá»‹ treo
CREATE INDEX IF NOT EXISTS idx_raw_scimago_journal_source_id
    ON raw_scimago_journal (source_id);

