"""
Migrate all data from Local PostgreSQL -> Vercel PostgreSQL.

Usage:
    python tools/migrate_local_to_vercel.py

Configuration:
    .env.local  -> LOCAL_DATABASE_URL
    .env.vercel -> VERCEL_DATABASE_URL
"""
import os
import sys

# Fix encoding for Windows console
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

import time
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(os.path.join(BASE_DIR, ".env.local"), override=False)
LOCAL_URL = os.getenv("LOCAL_DATABASE_URL") or os.getenv("DATABASE_URL")

load_dotenv(os.path.join(BASE_DIR, ".env.vercel"), override=True)
VERCEL_URL = os.getenv("VERCEL_DATABASE_URL") or os.getenv("DATABASE_URL")

if not LOCAL_URL or not VERCEL_URL or LOCAL_URL == VERCEL_URL:
    print("[ERROR] LOCAL_DATABASE_URL and VERCEL_DATABASE_URL must be different.")
    print("  Create .env.local with LOCAL_DATABASE_URL=<local_url>")
    print("  Create .env.vercel with VERCEL_DATABASE_URL=<vercel_url>")
    sys.exit(1)

# Table order respecting FK (parents first, children after)
TABLES_ORDER = [
    "Zone",
    "Subject_Area",
    "Subject_Category",
    "Publisher",
    "Ranking_Metric",
    "Journal",
    "Journal_Subject_Category",
    "Volume",
    "Issue",
    "Topic",
    "Article",
    "Author",
    "Author_Article",
    "Keyword",
    "Keyword_Article",
    "Sub_Topic",
    "Journal_Ranking",
    "Journal_Ranking_Subject_Category",
    "raw_scimago_journal",
]

# Tables with BIGINT GENERATED BY DEFAULT AS IDENTITY -> need OVERRIDING SYSTEM VALUE
IDENTITY_TABLES = {
    "Zone", "Subject_Area", "Subject_Category", "Publisher", "Ranking_Metric",
    "Journal", "Volume", "Issue", "Topic", "Article", "Author",
    "Keyword", "Journal_Ranking", "raw_scimago_journal",
}

CHUNK_SIZE = 500


def get_columns(conn, table_name):
    rows = conn.execute(text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = :tbl
        ORDER BY ordinal_position
    """), {"tbl": table_name}).fetchall()
    return [r[0] for r in rows]


def table_exists(conn, table_name):
    row = conn.execute(text(
        "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=:tbl"
    ), {"tbl": table_name}).fetchone()
    return row is not None


def count_rows(conn, table_name):
    if not table_exists(conn, table_name):
        return 0
    return conn.execute(text(f'SELECT COUNT(*) FROM "{table_name}"')).scalar()


def truncate_all(vercel_conn):
    print("\n[truncate] Clearing all data on Vercel DB...")
    for table in reversed(TABLES_ORDER):
        vercel_conn.execute(text(f'TRUNCATE TABLE "{table}" RESTART IDENTITY CASCADE'))
    vercel_conn.commit()
    print("[truncate] Done.")


def migrate_table(local_conn, vercel_conn, table_name):
    t0 = time.time()
    if not table_exists(local_conn, table_name):
        print(f"  [{table_name}] Table not found in source, skipping.")
        return
    total = count_rows(local_conn, table_name)
    if total == 0:
        print(f"  [{table_name}] Empty, skipping.")
        return

    cols = get_columns(local_conn, table_name)
    col_list = ", ".join(f'"{c}"' for c in cols)
    param_list = ", ".join(f":{c}" for c in cols)

    if table_name in IDENTITY_TABLES:
        insert_sql = (
            f'INSERT INTO "{table_name}" ({col_list}) '
            f'OVERRIDING SYSTEM VALUE VALUES ({param_list}) '
            f'ON CONFLICT DO NOTHING'
        )
    else:
        insert_sql = (
            f'INSERT INTO "{table_name}" ({col_list}) '
            f'VALUES ({param_list}) '
            f'ON CONFLICT DO NOTHING'
        )

    offset = 0
    inserted = 0
    while True:
        rows = local_conn.execute(text(
            f'SELECT {col_list} FROM "{table_name}" ORDER BY 1 LIMIT :lim OFFSET :off'
        ), {"lim": CHUNK_SIZE, "off": offset}).fetchall()

        if not rows:
            break

        batch = [dict(zip(cols, row)) for row in rows]
        vercel_conn.execute(text(insert_sql), batch)
        vercel_conn.commit()

        inserted += len(rows)
        pct = inserted / total * 100
        elapsed = time.time() - t0
        print(f"  [{table_name}] {inserted:,}/{total:,} ({pct:.1f}%) - {elapsed:.1f}s", end="\r")
        offset += CHUNK_SIZE

    elapsed = time.time() - t0
    print(f"  [{table_name}] OK {inserted:,} rows - {elapsed:.1f}s           ")


def run_migration():
    print("=" * 60)
    print("  LOCAL -> VERCEL DATABASE MIGRATION")
    print("=" * 60)
    print(f"  Source (Local) : {LOCAL_URL[:65]}...")
    print(f"  Target (Vercel): {VERCEL_URL[:65]}...")
    print()

    local_engine = create_engine(LOCAL_URL)
    vercel_engine = create_engine(VERCEL_URL)

    print("[check] Testing Local DB connection...")
    with local_engine.connect() as conn:
        db = conn.execute(text("SELECT current_database()")).scalar()
        print(f"  Local DB: {db} [OK]")

    print("[check] Testing Vercel DB connection...")
    with vercel_engine.connect() as conn:
        db = conn.execute(text("SELECT current_database()")).scalar()
        print(f"  Vercel DB: {db} [OK]")

    print()
    print("[info] Row counts in Local DB:")
    with local_engine.connect() as conn:
        for tbl in TABLES_ORDER:
            cnt = count_rows(conn, tbl)
            if cnt > 0:
                print(f"  {tbl}: {cnt:,}")

    print()
    ans = input("Proceed with migration? ALL Vercel data will be DELETED first. (y/N): ").strip().lower()
    if ans != "y":
        print("Cancelled.")
        return

    t_start = time.time()

    with vercel_engine.begin() as vercel_conn:
        vercel_conn.execute(text("SET session_replication_role = replica;"))
        truncate_all(vercel_conn)

    print("\n[migrate] Copying data...")
    with local_engine.connect() as local_conn:
        with vercel_engine.connect() as vercel_conn:
            vercel_conn.execute(text("SET session_replication_role = replica;"))
            vercel_conn.commit()

            for table in TABLES_ORDER:
                migrate_table(local_conn, vercel_conn, table)

            vercel_conn.execute(text("SET session_replication_role = DEFAULT;"))
            vercel_conn.commit()

    elapsed = time.time() - t_start
    print(f"\n[OK] Migration completed in {elapsed:.1f}s!")
    print()

    print("[verify] Row counts on Vercel DB after migration:")
    with vercel_engine.connect() as conn:
        for tbl in TABLES_ORDER:
            cnt = count_rows(conn, tbl)
            if cnt > 0:
                print(f"  {tbl}: {cnt:,}")


if __name__ == "__main__":
    run_migration()
